/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ex1;

import java.awt.Canvas;
import java.awt.Color;
import java.awt.Graphics;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author kosta
 */
public class Ex2_CanvasDemo extends javax.swing.JFrame implements Runnable{
    private int acrNum,x,y;  // ???? ê°???,x,yê°??? ê°??¸ì?¤ê¸°???´ì?? ë©¤ë??????? ???¥í????.
    private int arcX=0;  //???? ê°????? ???????? 0?¼ë? ì´?ê¸°í??????.
    private Thread t1;
    private Thread t2; // ?¤ë????ë¥? 2ê°?ë¥? ë§???.
    /**
     * Creates new form Ex1_GuiDraw
     */
    public Ex2_CanvasDemo() {
        initComponents();
        t1 = new Thread(this);  // t1?? ?????? run()?¨ì??ë¥? ?¬ì?????? ê²??? ê°??¸ì?? ?¤ë????.
        t2 =new Thread(){           // t2?? ?µë??´ë??´ë???¤ë?? ?µí?? run()?? t1ê³¼ë?? ?¤ë¥´ê²? ?°ë? ?¬ì?????? ?¤ë????.
            public void run(){
                for(int i=0;i<=36;i++){
                    try {
                        draw(300,100,i);  // xê°?ê³? yê°? ië¥? ?£ì??. ?´ë?¼í?µí?? ê°???ë¥? ?¤ì????ê³?,x,yë¥? ???¸í????, ìº?ë²??¤ì?? ê·¸ë¦¬ê²?????.
                        Thread.sleep(100); // ?????´ë?? ì¤???.
                    } catch (InterruptedException ex) {
                    }
                }
            }
        };
         // ê·¸ë¦¼?? ???? ê·¸ë?¤ì???ë¡? ????.
        }
        public synchronized void draw(int x,int y,int i) throws InterruptedException{
               acrNum=i*10;
               this.x=x;this.y=y;
               canvas1.repaint();
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        canvas1 = new java.awt.Canvas(){
            @Override
            public void update(Graphics g){
                paint(g);
            }
            @Override
            public void paint(Graphics g){
                g.setColor(Color.RED);
                g.drawArc(x,y, 100, 100, arcX, acrNum);
            }
        };

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        canvas1.setBackground(new java.awt.Color(102, 255, 204));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ex2_CanvasDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ex2_CanvasDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ex2_CanvasDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ex2_CanvasDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        Ex2_CanvasDemo c= new Ex2_CanvasDemo();
        // GUIê°?ì²´ë?? cë¡? ????.

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                    c.setVisible(true); // ???? GUIê°?ì²´ì??ì¹??? setvisible?? ?¨ì????.
            }
        });
       
       try {
            c.t1.start();
            c.t1.join();
            c.t2.start(); // ?´í?? ë©??¸ë??????????? ?¤ë????ë¥? ??????ë¡? ?¤í??????. ?¤ë? join?¼ë? ?¸í?? t1?? ??????ê¹?ì§? t2?? ?¤í???? ????.
        } catch (InterruptedException ex) {
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Canvas canvas1;
    // End of variables declaration//GEN-END:variables

    @Override  // t1?? ???? run() ?¨ì??ë¥? ?¬ì????
    public  void run() {
        for(int i=0;i<=36;i++){
            try {
                draw(100, 100, i); // t1?? x,yê°? 100,100?? ???? ê·¸ë¦¬??ë¡? ????.
               Thread.sleep(100);
            } catch (InterruptedException ex) {
            }
        }
    }
}
